/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121558-gd31983dc8e-20251029"
#endif /* AVUTIL_FFVERSION_H */
