name: Release

on:
  workflow_run:
    workflows: ["macos-build", "windows-build"]
    types:
      - completed
  push:
    branches:
      - issue178_build-test-failures

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow == 'macos-build' || github.event.workflow == 'windows-build' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download macOS build artifacts
        if: ${{ github.event.workflow == 'macos-build' && github.event.conclusion == 'success' }}
        uses: actions/download-artifact@v4
        with:
          name: SpeechTranscription_macos
          path: artifacts/macos

      - name: Download Windows build artifacts
        if: ${{ github.event.workflow == 'windows-build' && github.event.conclusion == 'success' }}
        uses: actions/download-artifact@v4
        with:
          name: SpeechTranscription_windows
          path: artifacts/windows

      - name: Verify Artifacts Directory Structure
        run: |
          echo "Root directory structure:"
          ls -R
          echo "Checking artifacts/macos:"
          ls -R artifacts/macos || echo "No macOS artifacts found."
          echo "Checking artifacts/windows:"
          ls -R artifacts/windows || echo "No Windows artifacts found."

      - name: Generate release notes
        run: |
          echo "## Automated Release" > release_notes.md
          echo "Build number: ${{ github.run_number }}" >> release_notes.md
          echo "Commit: ${{ github.sha }}" >> release_notes.md
          echo "## Downloads" >> release_notes.md
          echo "- macOS and Windows build artifacts included." >> release_notes.md

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Release and Upload Assets
        run: |
          gh release create v${{ github.run_number }} \
            -t "Release ${{ github.run_number }}" \
            -F release_notes.md \
            artifacts/macos/* \
            artifacts/windows/*
