name: Build, Test, and Release on macOS and Windows

on:
  push:
    branches:
      - issue168_automated-releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ['3.11', '3.12']
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install ffmpeg
          brew install portaudio

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ffmpeg
          choco install portaudio

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchaudio
          pip install -r requirements.txt
        continue-on-error: false

      - name: Install NLTK data
        run: |
          python -c "import nltk; nltk.download('all')"

      - name: Run tests with detailed output
        id: test
        run: |
          python -m pytest tests/ -v --junitxml=test-results.xml --capture=tee-sys > pytest-output.txt 2>&1
        continue-on-error: true

      - name: Display test output
        if: always()
        run: cat pytest-output.txt
        shell: bash

      - name: Store test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            test-results.xml
            pytest-output.txt
          if-no-files-found: warn

  release:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: test-results-*
          merge-multiple: true

      - name: Create project ZIP
        run: |
          # Create a ZIP of the entire project
          zip -r Saltify.zip . -x "*.git*" "*.pytest_cache*" "__pycache__/*" "*.pyc" "artifacts/*"

      - name: Generate release notes
        run: |
          echo "## Automated Release" > release_notes.md
          echo "Build number: ${{ github.run_number }}" >> release_notes.md
          echo "Commit: ${{ github.sha }}" >> release_notes.md
          echo "## Test Results" >> release_notes.md
          echo "See attached test results in artifacts" >> release_notes.md
          echo "## Downloads" >> release_notes.md
          echo "- Saltify.zip: Complete project source code" >> release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body_path: release_notes.md
          draft: false
          prerelease: true
          files: |
            artifacts/**
            Saltify.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}