name: Build, Test, and Release on macOS and Windows

on:
  push:
    branches:
      - issue168_automated-releases  # Trigger on push (merge) to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Run on macOS and Windows
        python-version: ['3.11', '3.12']    # Python versions to test with (3.11.9 or greater)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest  # Adjust based on your test framework

  release:
    needs: build  # Only run this after the build job succeeds
    runs-on: ubuntu-latest  # Only needs one OS to create the release

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this automatically
        with:
          tag_name: v${{ github.run_number }}  # Use the run number as the version
          release_name: Release ${{ github.run_number }}
          body: |
            Automatically generated release.
            - OS: ${{ matrix.os }}
            - Python Version: ${{ matrix.python-version }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./dist/  # Adjust this to your project's output directory
