name: Release

on:
  push:
    branches:
      - issue178_build-test-failures  # Specify your target branch
  workflow_run:
    workflows: ["macos-build", "windows-build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_run' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download macOS build artifacts
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: SpeechTranscription_macos
          path: artifacts/macos

      - name: Download Windows build artifacts
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: SpeechTranscription_windows
          path: artifacts/windows

      - name: Verify Artifacts Downloaded
        run: |
          echo "Listing contents of artifacts/macos:"
          ls artifacts/macos || echo "No macOS artifacts found."
          echo "Listing contents of artifacts/windows:"
          ls artifacts/windows || echo "No Windows artifacts found."

      - name: Generate release notes
        run: |
          echo "## Automated Release" > release_notes.md
          echo "Build number: ${{ github.run_number }}" >> release_notes.md
          echo "Commit: ${{ github.sha }}" >> release_notes.md
          echo "## Downloads" >> release_notes.md
          echo "- macOS and Windows build artifacts included." >> release_notes.md

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Release and Upload Assets
        run: |
          # Adjust file paths as needed to specify specific files instead of directories.
          gh release create v${{ github.run_number }} \
            -t "Release ${{ github.run_number }}" \
            -F release_notes.md \
            artifacts/macos/* \
            artifacts/windows/*
