name: Build, Test, and Release on macOS and Windows

on:
  push:
    branches:
      - main  # Trigger on merge to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest] 
        python-version: ['3.11', '3.12']    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest  # Modify if using a different test framework

  release:
    needs: build
    runs-on: ubuntu-latest  # Release only needs to run on one OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ github.run_number }} 
          release_name: Release ${{ github.run_number }}
          body: |
            Automatically generated release.
            - OS: ${{ matrix.os }}
            - Python Version: ${{ matrix.python-version }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact