name: Release

on:
  push:
    branches:
      - issue178_build-test-failures  # Specify your target branch
  workflow_run:
    workflows: ["macos-build", "windows-build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_run' }}
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify Node 20 explicitly

      - name: Checkout code
        uses: actions/checkout@v3  # Latest version

      - name: Download macOS build artifacts
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v3
        with:
          name: SpeechTranscription_macos
          path: artifacts/macos

      - name: Download Windows build artifacts
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v3
        with:
          name: SpeechTranscription_windows
          path: artifacts/windows

      - name: Create project ZIP
        run: |
          zip -r Saltify.zip . -x "*.git*" "*.pytest_cache*" "__pycache__/*" "*.pyc" "artifacts/*"

      - name: Generate release notes
        run: |
          echo "## Automated Release" > release_notes.md
          echo "Build number: ${{ github.run_number }}" >> release_notes.md
          echo "Commit: ${{ github.sha }}" >> release_notes.md
          echo "## Downloads" >> release_notes.md
          echo "- Saltify.zip: Complete project source code" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1  # Use latest stable version
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            artifacts/**
            Saltify.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
