name: Release

on:
  push:
    branches:
      - main
      - issue182_releaseprocess

permissions:
  contents: write
  packages: read
  actions: read

jobs:
  call-macos-build:
    uses: ./.github/workflows/macos-build.yml@main

  release:
    needs: [call-macos-build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Artifacts Directory
        run: mkdir -p artifacts/macos

      - name: Download macOS Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: SpeechTranscription_macos
          path: artifacts/macos

      - name: Validate macOS Artifact
        run: |
          if [ ! -f "artifacts/macos/Saltify" ]; then
            echo "Error: macOS artifact not found!" && exit 1
          fi

      - name: Debug Artifact Contents
        run: |
          echo "Listing contents of artifacts/macos:"
          ls -la artifacts/macos
          file artifacts/macos/Saltify

      - name: Create macOS ZIP
        run: |
          zip -j artifacts/Saltify_macos.zip artifacts/macos/Saltify

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Build Number: ${{ github.run_number }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
       
