on:
  push:
    branches:
      - main
      - fix-exe
      - testingv4artifact
      - issue169_dependency
      - issue178_build-test-failures

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.7

      - name: Install Java
        shell: powershell
        run: |
          if (-not (Get-Command java -ErrorAction SilentlyContinue)) {
            Write-Host "Java not found, installing JDK 11..."
            choco install jdk11 -y
          } else {
            Write-Host "Java is already installed."
          }

      - name: Install NLTK
        run: |
          pip install nltk
          python -m nltk.downloader punkt

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller importlib-metadata sacremoses tokenizers
          pip uninstall -y typing

      - name: Build Windows Executable
        run: |
          pyinstaller --name Saltify --windowed --noconfirm --onefile -c ^
            --copy-metadata torch ^
            --copy-metadata tqdm ^
            --copy-metadata regex ^
            --copy-metadata sacremoses ^
            --copy-metadata requests ^
            --copy-metadata packaging ^
            --copy-metadata filelock ^
            --copy-metadata numpy ^
            --copy-metadata tokenizers ^
            --copy-metadata importlib_metadata ^
            --collect-data sv_ttk ^
            --recursive-copy-metadata openai-whisper ^
            --collect-data whisper GUI.py

      - name: Add additional build assets
        shell: cmd
        run: |
          robocopy build_assets dist/Saltify /e /v
          mkdir dist\Saltify\_internal\lightning_fabric
          robocopy dist/Saltify/_internal/lightning dist/Saltify/_internal/lightning_fabric /e /v
          mkdir dist\Saltify\_internal\pattern\text\en\
          move dist\Saltify\en-model.slp dist\Saltify\_internal\pattern\text\en\

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SpeechTranscription_windows
          path: dist/Saltify.exe

      - name: Upload zipped exe (optional)
        uses: actions/upload-artifact@v4
        with:
          name: Saltify-windows-zip
          path: Saltify_windows.zip
